language: android

jdk:
  - oraclejdk8

before_install:
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo $GPG_SECRET_KEYS | base64 --decode | gpg --import
  - echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust

script:
  - ./gradlew build --stacktrace

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then ./gradlew uploadArchives --no-daemon --no-parallel

notifications:
  email: false

cache:
  directories:
    - $HOME/.gradle
