language: android

jdk:
  - oraclejdk8

before_install:
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"

android:
  components:
    - build-tools-29.0.1

script:
  - ./gradlew build --stacktrace

after_success:
  - ./.travis/deploy.sh

notifications:
  email: false

cache:
  directories:
    - $HOME/.gradle

env:
  global:
    - secure: xdiK6NHTAZghDGz6OuEILSPEkv5ziBp+oLWganXzGU7KuTpmSKSp+sdhs8ugBGzxUczI7LMKVqyAUOJxp+bENcwfUhWh6N7roxVgEARJIv/knc3VNshIGQqSlSI46SyWEIktObVczfF/XG250T7X3g7Jr1PEK/yJbtcRZ8I0ZEb0k4/iXxGAmTz7OHlZzoJp2XzGe0JXzZqJ6LpNf/yUrdjFGj/xwiFvpOqQnE54rrLi2fr9p+81ZxFxg9ind/qZUwyLmGTnuNc8miYePgAlh8kPvC+8x4ucs/+zcjd0p2onR9Evh4UA8UwdzvT0TIbOdEd8q3cBbaQBoSGPz75FTIwPyvXSaEAyGsiq6sYqoeWHO/QYUof9n6WMC4k9zmJJynYChGctCQPKn9ps2DxGoJbNOe54Y5Et859LgGpksIcG41mfw25Fe77xcdE8fIO5Fwe7RRHIi7uev655xer8DvEtdPNQN95Jfs8N99YBuL5nSDq9bNE1nc3uQ7ZApM9jxB9gK376PzvWhD9QOdx1MZdhLb2HDrrPTAe7kbGEmzMU31+pvZdCZKjli73XgxJYFggdjJVybrhqd/ZJx3tX3KMvKHDE0Bv8kcYyuAEHNxAtm9WaLTg4O+SzGpyG6M2Xlka2IqdDRwXqp/43RTUKw66/Wayb9YStEW6lY4dD5hU=
    - secure: NsHI/+mQ8S5MTYXhuS9RBOMtXHOFwxOXObQ1z1r02QlJfctrjfv5XpYJrIU2BHRbLTxtBdy99Vsdb/6cyV5YJKINzVlo8QM50VNcLQhaAdzO5FPrcar0HkEbTkXCZzOyGZPxiQ2x2/MnVVLUFOI9fxHG3FCukmIL0+iNNCNipyJFVfOhJFZDz46GgFSD5oUwMJdsPhATxa8qx9hprxgJZ/8e3Xg7NjLEfACssYQ+XMEdU7yXbLL59lEu2/+4+nYAoKZVd5vgvZ6GbFguOGjAGlBYeeCZkicu+qoiW19pvaQpmPPIotnRfKoIooDuE+DhbA2duetvHdxg6o8W2d8lYC7gHnkKedzH9smur830OaQgbl0Mb6YreqTAhxDqEZyd9vffeuYD8EupnZacqbV7Hno/Oyjf8JnZQgK7lzaMJH7I3xjiY89rkdgkLRKEgSoXfSc3HOwtigR4ruRBtjimo22pV7AbzhZBi1ybbC6oMVl1bw4991X9gl2zfFmcgsJXBjg8p3cT5njTXYM4RgmZfxVArbXTRdAfbJcTeezobdSkRo6axiRXSEW5Y0b5CPSunEyJi9sSFY3aQRQH1VZGVW3PijudbwjhkL7P3djNYEPhUZ4yISvQ1S0vC6YVxc05pjON9tndBlbp6Vcv0XWsik9HynL6r9rgvbDpFI0a+TA=
    - secure: U+2bXEf6EiQvqhjPh6DvOi24sOJmmzYjiGUEP1u2OwarNuZW2skbvt1OJ9TZekxS3vAVfT5CrUp92hay3bo86ukR29WQkB+bb/Tzet8QffQPZ3V/BIC2rhx9eT1BhdCWCmFMNQxZa1WYyIyDaxM374QLGLCA4nxz24iWhWpS5NuaR1Elij7+xAiMisF9LPiIlAsCtLs+Y2kHJ3/Od79EN4YiRuZBpZKsdAQE1/OXFpm9M/RqYignZ+QokYGR9/OkNmQ9tRkjyZwH5Bl36Kv9ieQwFPJ3HlxTzB0+Rksfa7ujMeY1ktaT3fKmA65vXWP+zBKnn260+UwiAFYLnrB8o1/hsniOORncTLQS24IiveCyTB+jC6mt+sg0wWAPcm7ThlFWx3SLXFJYRm5pjSg4Bk1M5xz1bjOAbMFaYLiN7zQ/cwotF/7ieHny9+iI0X8b7ivN3Vo5luQHIWCq43+boPC+7Gg94W/42tGlbs34aAtaEb5WW7zdXDRs4BwO57B7tDYgRjXSVsHqt6OURMdfuB6j8BZ0lkaBl3z4ahsIYWrOKZM4K/odLjebiD9OxwDWRubHpwIXp9ABNtTMK8zVeyci2V+71Cw4fotY4W4dspKZhBvYXGy3WykInZ5bnRvG9T1sccUR/JNXBUJZx3OETKp1HEXnmf1U+Jx2S34flT0=
    - secure: hO0s+5rAw9Au41McbppavMIY9U9tLAolRuQrzI/We9+6OfHDui2uA+4KBBWgJLnPgjS2RV54d70/686L/MLmZSMelpzKue5/IVUwni2UsUfyyAsoE5TYy09L5QeiRyXNeOHWU/HxVOri3YeMh1wgAaEqHKMVjveLfFMGY79gp859IC71YU4duqq+Dv4Wm9I6M7HaFs1FvF/Zloulvx1oIeHPaCJ9PU+darq63gqcFFHDknyIx5Upp5aquv4EahxgVDMj4AFDYispsYRuP0wVC2z3t6MieMXgLPHRq+thtWR7licsNIXoZvDr18GRPAand4/Ivnu+HkzQGSaeoJ8SjhOODlB1LAgQXsnddvCeWJ9YevYT0EwzG1JjsxsNINaE8eAOb08Y8ZGFeGi5GP8/MN+/6Imkq8qQwiveGOX+eJE3HC88YQsk99CmL+Atrb6wITvRAf4R4P5iTm5qGANHQqjN8wYNWYeHVvj3ZANrdlZt1igOQaweDsG37Ul32qj5R7BXksQ7NtNddxZd+FYlunN791FsCjRz4+UUd43PpPzNS6tYvNehrUuqdTX35CcElDOrgaUJIiB1daKIt2M95ZjWbjMaKzb5KUqfjpj8gjb9CK63XwpRxK3OA+XAarh5GjhB3QmLzGZcipo2GIWB16LdyUGjj5jUMxWGSvWZJdo=
