language: android

jdk:
 - oraclejdk8

before_install:
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"

script:
 - ./gradlew build --stacktrace

notifications:
  email: false

cache:
  directories:
    - $HOME/.gradle
