name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Setup variables for versions
      run: |
        VERSION_NAME=`cat gradle.properties | grep "VERSION_NAME" | cut -d'=' -f2`
        IS_SNAPSHOT=$( [[ "$VERSION_NAME" == *"SNAPSHOT"* ]] && echo "true" || echo "false" )
        IS_NEW_VERSION=$( git tag -l | grep -q "^$VERSION_NAME$" && echo "false" || echo "true" )
        echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
        echo "IS_SNAPSHOT=$IS_SNAPSHOT" >> $GITHUB_ENV
        echo "IS_NEW_VERSION=$IS_NEW_VERSION" >> $GITHUB_ENV

    - name: Generate release notes
      if: ${{ github.event_name != 'pull_request' && env.IS_SNAPSHOT == 'false'  }}
      run: ./gradlew -q getChangelog >> RELEASE_NOTES.md

    - name: Release on Github
      if: ${{ github.event_name != 'pull_request' && env.IS_SNAPSHOT == 'false' && env.IS_NEW_VERSION == 'true' }}
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.VERSION_NAME }}
        body_path: RELEASE_NOTES.md
        files: |
          debugdrawer/build/outputs/aar/debugdrawer-debug.aar
          debugdrawer-leakcanary/build/outputs/aar/debugdrawer-leakcanary-release.aar
          debugdrawer-okhttp-logger/build/outputs/aar/debugdrawer-okhttp-logger-release.aar
          debugdrawer-retrofit/build/outputs/aar/debugdrawer-retrofit-release.aar
          debugdrawer-timber/build/outputs/aar/debugdrawer-timber-release.aar

    - name: Publish to sonatype
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        echo signingInMemoryKeyPassword="${GPG_PASSWORD}" >> "$HOME/.gradle/gradle.properties"
        echo signingInMemoryKey="${GPG_KEY}" >> "$HOME/.gradle/gradle.properties"
        echo mavenCentralUsername="${MAVEN_CENTRAL_USERNAME}" >> "$HOME/.gradle/gradle.properties"
        echo mavenCentralPassword="${MAVEN_CENTRAL_PASSWORD}" >> "$HOME/.gradle/gradle.properties"
        ./gradlew androidSourcesJar androidJavadocJar publish --info --no-daemon --no-parallel
      env:
        GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
        GPG_KEY: ${{ secrets.GPG_KEY }}
        MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        
    - name: Close and release repository
      if: ${{ github.event_name != 'pull_request' && env.IS_SNAPSHOT == 'false' }}
      run: |
        ./gradlew closeAndReleaseRepository --info --no-daemon --no-parallel
      env:
        MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
